# Production overrides for docker-compose.yml
# Use with: docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d

services:
  cw_hsq_app:
    build:
      target: production  # Use production stage of Dockerfile
    environment:
      NODE_ENV: production
      # Phase 8 Production Configuration Overrides
      CONFIG_BACKUP_ENABLED: true
      CIRCUIT_BREAKER_ENABLED: true
      AUDIT_LOG_RETENTION_DAYS: 365
      ENCRYPTION_KEY: ${ENCRYPTION_KEY_PRODUCTION}
    volumes:
      # Remove development volume mounts
      - cw_hsq_app_logs:/app/logs
      # Phase 8: Enhanced production backup storage
      - cw_hsq_config_backups:/app/backups:rw
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '2.0'
        reservations:
          memory: 512M
          cpus: '1.0'
      replicas: 2  # Run multiple instances for high availability

  cw_hsq_dashboard:
    environment:
      NODE_ENV: production
      # Phase 8 Production Dashboard Configuration
      NEXT_PUBLIC_ENABLE_CONFIGURATION_UI: true
      NEXT_PUBLIC_ENABLE_HEALTH_DASHBOARD: true
      NEXT_PUBLIC_ENABLE_AUDIT_LOGS: true
      NEXT_PUBLIC_CONFIGURATION_WIZARD_ENABLED: true
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'

  cw_hsq_postgres:
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '1.0'
    command: >
      postgres
      -c max_connections=200
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.7
      -c wal_buffers=16MB
      -c default_statistics_target=100
      -c random_page_cost=1.1
      -c effective_io_concurrency=200

  cw_hsq_redis:
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'
    # Phase 8: Enhanced Redis configuration for OAuth state and configuration caching
    command: >
      redis-server
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --save 900 1
      --save 300 10
      --save 60 10000
      --appendonly yes
      --auto-aof-rewrite-percentage 100
      --auto-aof-rewrite-min-size 64mb

  cw_hsq_nginx:
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.5'
        reservations:
          memory: 64M
          cpus: '0.25'

volumes:
  cw_hsq_app_logs: